spring.application.name=BankingSystem

server.port = 8080

spring.datasource.url = ${DB_URL:jdbc:mysql://mysql-3d40e215-kumarmathan2206-acd4.b.aivencloud.com:12483/defaultdb?sslMode=REQUIRED}
spring.datasource.username = ${DB_USER:avnadmin}
spring.datasource.password = ${DB_PASS:password_goes_here}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.database-platform = org.hibernate.dialect.MySQLDialect
