spring.application.name=BankingSystem

server.port = 8080

spring.datasource.url=${DB_URL:jdbc:mysql://mysql-3d40e215-kumarmathan2206-acd4.b.aivencloud.com:12483/defaultdb?useSSL=true&requireSSL=true&allowPublicKeyRetrieval=true&connectTimeout=10000}
spring.datasource.username=${DB_USERNAME:avnadmin}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.database-platform = org.hibernate.dialect.MySQLDialect
